### ISSUE TITLE
Not showing..

### ISSUE THREAD

**Issue by pdichone** [delight-im/AppRater#1]
Hi there,

Thank so much for creating this awesome tool! I am having an issue.  The alert dialog is just not showing.  I made sure to add ".show", but no luck.  Also, I am using fragments, I don't know if that's where the problem is?

Any guidance would be highly appreciated.

Thanks

**Comment by mahekmshah** [comment]
This is a good library, however I am seeing a small issue.

If I do Later and then I decide no I want to rate now then the dialog is not shown unless the launch time of I guess 2days is up. My guess is this would be the same behavior for Never also, though IMO never means never prompt me but the user can choose to rate whenever he/she wants to.

NOTE: I am doing setDaysBeforePrompt(0); and setLaunchesBeforePrompt(0) before calling show, everytime user clicks on rate us.

Is this a bug or am I doing something incorrect. 

Thanks!
