### ISSUE TITLE
Publish library to maven central for Android Studio gradle dependency support

### ISSUE THREAD

**Issue by justinharrison** [delight-im/AppRater#4]
I think it would be great if this library could be published to the Maven Central repository so that it could be included as a gradle dependency for Android Studio projects. This makes things much simpler, and then you don't have to include source code, or manually build a jar to include with your project.

**Comment by mwaclawek** [comment]
The JARs which are available now make this issue (at least partly) obsolete.

While dependency management via Maven Central may be even more comfortable (especially when updates are available), the JARs should be sufficient for this library.
