### ISSUE TITLE
Difference between "show" and "demo"

### ISSUE THREAD

**Issue by TroniPM** [delight-im/AppRater#5]
What is the difference between "show" and "demo"? I mean, if i call the "show", even on real device, it doesn't show the alertdialog. If i call "demo", always shows the alertdialog, despising "DaysBeforePrompt" and "LaunchesBeforePrompt"'s setup. Yes, i'm in app development. So, when i put the apk on google store (example), the alertdialog will appear normally? How is it work?

Thanks in advance.

**Comment by mwaclawek** [comment]
`show()` is for production usage and meets the criteria of days before prompt and launches before prompt. Use this when publishing your app.

`demo()` is for a preview during development only and ignores those criteria, as you already said. Don't use this when publishing your app, as the dialog will *always* show up.

https://github.com/delight-im/AppRater#preview-usage-during-development
