### ISSUE TITLE
Minor change to Readme

### ISSUE THREAD

**Issue by rmohan80** [delight-im/AppRater#7]
Great App!

Minor change to readme. I think it should be:

appRater.show();

rather than 

mAlertDialog = appRater.show();

because mAlertDialog has never been defined. Somebody copy pasting this won't know :)

**Comment by mwaclawek** [comment]
Thank you!

Like this? -- https://github.com/delight-im/AppRater/commit/3e26c47c9b206323bcacda51456da3a231a76bd4

**Comment by rmohan80** [comment]
Looks good!
