### ISSUE TITLE
Detect if app is already rated

### ISSUE THREAD

**Issue by adrcotfas** [delight-im/AppRater#8]
Hi,

A cool feature would be to check if the app is already rated or not and only if it's not rated to open the AppRater dialog.
For example, if the user clicks on the "Rate now" button and there is no internet connection or the user simply changes his mind, the app will remain unrated and no further notification dialog will appear.
Do you plan to implement this?

**Comment by ocram** [comment]
Thanks for your feature request!

I wish that was possible. But unfortunately, Google does not provide the APIs or data that would be required for this.
