### ISSUE TITLE
class AppRater is public, should be declared in a file named AppRater.java

### ISSUE THREAD

**Issue by abedputra** [delight-im/AppRater#9]
Error:(25, 8) error: class AppRater is public, should be declared in a file named AppRater.java. how to fix this?
thanks

**Comment by ocram** [comment]
Thanks for your question!

As you can see in the source code, the class _is_ already in a file with that correct name. So there shouldn't be anything wrong unless you renamed either the file or the class.

Apart from that, if you just want to _use_ this library and not work on it or debug it, you can simply include one of the JARs in your app -- no need to include the source code.

Does that help?

**Comment by abedputra** [comment]
ok thanks
